name: Run ROC Sensor in GitHub Actions

on:
  workflow_dispatch:

jobs:
  run-roc:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare config file
        shell: bash
        run: |
          mkdir -p /tmp/roc-output /tmp/roc-config
          cat > /tmp/roc-config/pattern.yaml <<'EOF'
patterns:
  - id: "api_key"
    regex: "(?i)api[_-]?key\\s*[:=]\\s*[A-Za-z0-9\\-_]{16,}"
  - id: "authorization_bearer"
    regex: "Bearer\\s+[A-Za-z0-9\\-._~+/]+=*"
  - id: "email"
    regex: "[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}"
EOF

          echo "Pattern file written at /tmp/roc-config/pattern.yaml"
          cat /tmp/roc-config/pattern.yaml
          ls -l /tmp/roc-config/

      - name: Run ROC container (privileged)
        shell: bash
        run: |
          echo "Starting ROC privileged container..."
          docker run -d --name roc-test \
            --privileged \
            --pid=host \
            --network=host \
            -v /proc:/proc \
            -v /sys:/sys \
            -v /lib:/lib:ro \
            -v /usr/lib:/usr/lib:ro \
            -v /tmp/roc-output:/tmp/roc-output \
            -v /tmp/roc-config:/roc-config:ro \
            hanshal785/roc:latest \
            --server-url https://api.codexsecurity.io \
            --api-key dummyapikey1234567890 \
            --patterns /roc-config/pattern.yaml \
            --watch /tmp/roc-output

      - name: Simulate curl traffic
        shell: bash
        run: |
          echo "Generating curl traffic..."
          curl -s https://example.com > /dev/null || true
          curl -s -X POST https://httpbin.org/post -d '{"roc":"test"}' \
            -H "Content-Type: application/json" > /dev/null || true

      - name: Print ROC logs
        shell: bash
        run: |
          echo "Fetching ROC container logs..."
          docker logs roc-test || true

      - name: Cleanup
        if: always()
        shell: bash
        run: |
          docker rm -f roc-test || true
          rm -rf /tmp/roc-output /tmp/roc-config
