name: Build with Cached Docker Image

on: [pushwe]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Docker image
        id: cache-docker
        uses: actions/cache@v3
        with:
          path: /tmp/docker-image
          key: docker-codex-${{ hashFiles('**/Dockerfile') }}
          restore-keys: docker-codex-

      - name: Load cached Docker image (if exists)
        if: steps.cache-docker.outputs.cache-hit == 'true'
        run: |
          docker load -i /tmp/docker-image/codex.tar

      - name: Pull image if not cached
        if: steps.cache-docker.outputs.cache-hit != 'true'
        run: |
          mkdir -p /tmp/docker-image
          docker pull public.ecr.aws/f9o7b7m0/codex
          docker save public.ecr.aws/f9o7b7m0/codex -o /tmp/docker-image/codex.tar
