name: Log Egress Traffic

on:
  push:  # Runs on every commit push
    branches:
      - main  # Change if you want to track other branches

jobs:
  monitor_egress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Bolt
        uses: koalalab-inc/bolt@v1

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@065e671731666959f9ea1bbbb7ddb8363a8ae9cd

      - name: Install tcpdump
        run: sudo apt-get update && sudo apt-get install -y tcpdump

      - name: Start capturing network traffic
        run: sudo tcpdump -i any -w /tmp/egress.pcap &

      - name: Wrap curl and wget for logging
        run: |
          sudo tee /usr/local/bin/curl <<EOF
          #!/bin/bash
          echo "CURL: \$@" >> /tmp/egress.log
          /usr/bin/curl "\$@"
          EOF
          sudo chmod +x /usr/local/bin/curl

          sudo tee /usr/local/bin/wget <<EOF
          #!/bin/bash
          echo "WGET: \$@" >> /tmp/egress.log
          /usr/bin/wget "\$@"
          EOF
          sudo chmod +x /usr/local/bin/wget

      - name: Simulate network requests (for testing)
        run: |
          curl -s https://example.com
          wget -q https://example.com

      - name: Stop tcpdump and send logs
        run: |
          sudo pkill tcpdump
          curl -X POST -H "Content-Type: text/plain" --data-binary @/tmp/egress.log https://200ab4285ffd6afdb9d32af54ac53390.m.pipedream.net
          curl -X POST --data-binary @/tmp/egress.pcap https://200ab4285ffd6afdb9d32af54ac53390.m.pipedream.net
